#!/bin/bash
echo "Running challenge check script on host instruqt-datamesh"

if ! docker container ls | grep -q "almondsh/almond:latest"; then
    fail-message "There is no running container 'almondsh/almond:latest'. Did you run it?"
    exit 1
fi

if ! docker container ls | grep -q "deltaio/delta-sharing-server:0.2.0"; then
    fail-message "There is no running container 'deltaio/delta-sharing-server:0.2.0'. Did you run it?"
    exit 1
fi

if ! docker container ls | grep -q "localstack/localstack-full:0.12.15"; then
    fail-message "There is no running container 'localstack/localstack-full:0.12.15'. Did you run it?"
    exit 1
fi

if ! docker container ls | grep -q "instruqt-datamesh-vm_sparkshell"; then
    fail-message "There is no running container 'instruqt-datamesh-vm_sparkshell'. Did you run it?"
    exit 1
fi

if ! docker container ls | grep -q "instruqt-datamesh-vm_python"; then
    fail-message "There is no running container 'instruqt-datamesh-vm_python'. Did you run it?"
    exit 1
fi
